# Change these settings from the Config GUI provided in MapAssist
HotkeyConfiguration:
  ToggleKey: '|'
  AreaLevelKey: '['
  ZoomInKey: Num +
  ZoomOutKey: Num -
HiddenAreas: []
RenderingConfiguration:
  Opacity: 0.2
  IconOpacity: 0.15
  OverlayMode: false
  Position: TopRight
  MonsterHealthBar: false
  ToggleViaInGameMap: false
  ToggleViaInGamePanels: true
  StickToLastGameWindow: false
  Size: 150
  ZoomLevel: 1
  BuffPosition: Bottom
  BuffSize: 0
  LinesMode: All
MapConfiguration:
  SuperUniqueMonster:
    IconOutlineColor: Yellow
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  UniqueMonster:
    IconOutlineColor: DarkOrange
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  ChampionMonster:
    IconOutlineColor: DarkRed
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
  MinionMonster:
    IconOutlineColor: 255, 150, 150
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  NormalMonster:
    IconOutlineColor: Gray
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  Npc:
    IconOutlineColor: 196, 196, 196
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
    LabelColor: 199, 179, 119
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  NextArea:
    IconColor: SpringGreen
    IconShape: Square
    IconSize: 5
    LineColor: SpringGreen
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: SpringGreen
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  PreviousArea:
    IconColor: Violet
    IconShape: Square
    IconSize: 5
    LabelColor: Violet
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  Waypoint:
    IconColor: SteelBlue
    IconShape: Square
    IconSize: 5
  Quest:
    LineColor: Tomato
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Tomato
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  Player:
    IconOutlineColor: 33, 136, 253
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Chartreuse
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  PartyPlayer:
    IconOutlineColor: Chartreuse
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Chartreuse
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  NonPartyPlayer:
    IconOutlineColor: Orange
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LabelColor: Orange
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  HostilePlayer:
    IconOutlineColor: Red
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LineColor: Red
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Red
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  MyMerc:
    IconOutlineColor: 77, 120, 124
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  OtherMercs:
    IconOutlineColor: 81, 167, 60
    IconShape: Cross
    IconSize: 6
    IconThickness: 1
  Corpse:
    IconOutlineColor: Magenta
    IconShape: Cross
    IconSize: 6
    IconThickness: 2
    LineColor: Magenta
    LineThickness: 2
    ArrowHeadSize: 15
    LabelColor: Magenta
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  Portal:
    IconOutlineColor: Yellow
    IconShape: Portal
    IconSize: 3
    IconThickness: 2
    LabelColor: Yellow
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  SuperChest:
    IconColor: 17, 255, 0
    IconShape: Square
    IconSize: 4
  NormalChest:
    IconColor: 17, 128, 0
    IconShape: Square
    IconSize: 3
  LockedChest:
    IconColor: Maroon
    IconShape: Square
    IconSize: 3
  TrappedChest:
    IconColor: Red
    IconShape: Square
    IconSize: 4
  Shrine:
    IconColor: 255, 218, 100
    IconShape: Polygon
    IconSize: 5
    LabelColor: 255, 218, 100
    LabelFontSize: 14
    LabelFont: Formal 436
    LabelTextShadow: true
  ArmorWeapRack:
    IconColor: 132, 132, 132
    IconShape: Square
    IconSize: 4
  Item:
    IconColor: DarkOrange
    IconShape: Ellipse
    IconSize: 4
    LabelFontSize: 16
    LabelFont: Exocet Blizzard Mixed Caps
    LabelTextShadow: true
ItemLog:
  Enabled: true
  Position: TopLeft
  FilterFileName: ItemFilter.yaml
  CheckVendorItems: true
  CheckItemOnIdentify: true
  PlaySoundOnDrop: false
  SoundFile: ''
  SoundVolume: 0
  DisplayForSeconds: .1
  LabelFont: Exocet Blizzard Mixed Caps
  LabelFontSize: 16
  LabelTextShadow: true
MapColorConfiguration:
  Border: 255, 255, 255
GameInfo:
  Position: TopLeft
  ShowGameName: false
  ShowArea: false
  ShowDifficulty: false
  ShowGameIP: false
  HuntingIP: 0.0.0.0
  ShowAreaLevel: false
  ShowOverlayFPS: false
  LabelFont: Exocet Blizzard Mixed Caps
  LabelFontSize: 16
  LabelTextShadow: true
D2Path: ''
LanguageCode: enUS
