name: Rebase after merge

on: 
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  rebase:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    name: Rebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: develop
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    - name: Rebase
      run: |
        git config --global user.email "${GITHUB_ACTOR}"
        git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
        git status
        git rebase origin/main
        git status
        git push --force-with-lease origin HEAD:develop
        git status
