
from item.types import ItemType, ItemQuality, ItemMode, InventoryPage, BodyLoc, StashType, ItemFlag, Stat, SkillTree

# If you have an item listed here and it is identified, these rules will be applied to it.
# If any of the rules in the list match the item, the highest priority among them will be used.
# The rules should be functions that take in an item and return a boolean. 
#
# Example rule:
#     ItemType.GrandCharm: [
#         lambda item: item.check(Stat.MaxDamage, ">=", 10) and item.check(Stat.MaxLife, ">=", 10)
#     ]
#
IDENTIFIED_ITEMS = {
    ItemType.GrandCharm: [
        lambda item: item.check(Stat.MaxDamage, ">=", 10) and item.check(Stat.MaxLife, ">=", 20),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.PaladinCombatSkills),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.SorceressCold),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.SorceressFire),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.SorceressLightning),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.AmazonJavelinAndSpear) and item.check(Stat.MaxLife, ">=", 20),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.NecromancerPoisonAndBone) and item.check(Stat.MaxLife, ">=", 20),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.NecromancerSummoning) and item.check(Stat.MaxLife, ">=", 30),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.BarbarianWarcries) and item.check(Stat.MaxLife, ">=", 30),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.BarbarianWarcries) and item.check(Stat.GoldFind, ">=", 20),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.DruidElemental) and item.check(Stat.MaxLife, ">=", 20),
        lambda item: item.check(Stat.AddSkillTab, "==", SkillTree.AssassinTraps) and item.check(Stat.MaxLife, ">=", 20),
    ],
    ItemType.SmallCharm: [
        lambda item: item.check(Stat.MaxLife, ">=", 20) and (item.check(Stat.FireResist, ">=", 10) or item.check(Stat.LightningResist, ">=", 10)),
        lambda item: item.check(Stat.MagicFind, ">=", 7) and (item.check(Stat.MaxDamage, ">=", 3) or item.check(Stat.FasterHitRecovery, ">=", 10)),
        lambda item: item.check(Stat.AllResist, ">=", 5), # 5@
        lambda item: item.check(Stat.MagicFind, ">=", 7), # 7 MF
        lambda item: item.check(Stat.MaxLife, ">=", 20), # 20 Life
        lambda item: item.check(Stat.MaxLife, ">=", 18) and item.check(Stat.MaxMana, ">=", 17), # 18+ life/17 mana SC
        lambda item: item.check(Stat.MaxLife, ">=", 15) and item.check(Stat.MaxDamage, ">=", 3), # 15+ life/3max SC
    ],
    ItemType.Ring: [
        # Unique Rings
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.AllSkills, ">=", 1) and item.check(Stat.MaxMana, ">=", 20), # SoJ
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.AllSkills, ">=", 1) and item.check(Stat.LifeSteal, ">=", 3), # BK Ring
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.AbsorbLightningPercent, ">=", 15), # Wisp Projector
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.Dexterity, ">=", 20) and item.check(Stat.AttackRating, ">=", 250), # Raven Frost
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.MagicDamageReduction, ">=", 15), # Dwarf Star
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.MagicFind, ">=", 30) and item.check(Stat.AttackRating, ">=", 75), # Nagel
    ],
    ItemType.Amulet: [
        # Unique Amulets
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.AllSkills, ">=", 2) and item.check(Stat.AllResist, ">=", 20), # Mara's Kaleidoscope
        lambda item: item.quality == ItemQuality.Unique and item.check(Stat.AllSkills, ">=", 1) and item.check(Stat.LightningResist, ">=", 25), # Highlord's Wrath
    ],
}

POTIONS = {
    ItemType.FullRejuvenationPotion: 1,
    ItemType.RejuvenationPotion: 1,
    ItemType.SuperHealingPotion: 1,
    ItemType.SuperManaPotion: 1,
    ItemType.GreaterHealingPotion: 0,
    ItemType.GreaterManaPotion: 0,
}

BASIC_ITEMS = {
    ItemType.KeyOfTerror: 1,
    ItemType.KeyOfHate: 1,
    ItemType.KeyOfDestruction: 1,
    
    ItemType.TwistedEssenceOfSuffering: 1,
    ItemType.ChargedEssenceOfHatred: 1,
    ItemType.BurningEssenceOfTerror: 1,
    ItemType.FesteringEssenceOfDestruction: 1,

    ItemType.ElRune: 0,
    ItemType.EldRune: 0,
    ItemType.TirRune: 0,
    ItemType.NefRune: 0,
    ItemType.EthRune: 0,
    ItemType.IthRune: 0,
    ItemType.TalRune: 0,
    ItemType.RalRune: 0,
    ItemType.OrtRune: 0,
    ItemType.ThulRune: 0,
    ItemType.AmnRune: 0,
    ItemType.SolRune: 0,
    ItemType.ShaelRune: 0,
    ItemType.DolRune: 0,
    ItemType.HelRune: 0,
    ItemType.IoRune: 0,
    ItemType.LumRune: 0,
    ItemType.KoRune: 0,
    ItemType.FalRune: 0,
    ItemType.LemRune: 1,
    ItemType.PulRune: 1,
    ItemType.UmRune: 1,
    ItemType.MalRune: 1,
    ItemType.IstRune: 1,
    ItemType.GulRune: 1,
    ItemType.VexRune: 2,
    ItemType.OhmRune: 2,
    ItemType.LoRune: 2,
    ItemType.SurRune: 2,
    ItemType.BerRune: 2,
    ItemType.JahRune: 2,
    ItemType.ChamRune: 2,
    ItemType.ZodRune: 2,

    ItemType.ChippedAmethyst: 0,
    ItemType.ChippedTopaz: 0,
    ItemType.ChippedSapphire: 0,
    ItemType.ChippedEmerald: 0,
    ItemType.ChippedRuby: 0,
    ItemType.ChippedDiamond: 0,

    ItemType.FlawedAmethyst: 0,
    ItemType.FlawedTopaz: 0,
    ItemType.FlawedSapphire: 0,
    ItemType.FlawedEmerald: 0,
    ItemType.FlawedRuby: 0,
    ItemType.FlawedDiamond: 0,

    ItemType.Amethyst: 0,
    ItemType.Topaz: 0,
    ItemType.Sapphire: 0,
    ItemType.Emerald: 0,
    ItemType.Ruby: 0,
    ItemType.Diamond: 0,

    ItemType.FlawlessAmethyst: 0,
    ItemType.FlawlessTopaz: 0,
    ItemType.FlawlessSapphire: 0,
    ItemType.FlawlessEmerald: 0,
    ItemType.FlawlessRuby: 0,
    ItemType.FlawlessDiamond: 0,

    ItemType.PerfectAmethyst: 1,
    ItemType.PerfectTopaz: 1,
    ItemType.PerfectSapphire: 1,
    ItemType.PerfectEmerald: 1,
    ItemType.PerfectRuby: 1,
    ItemType.PerfectDiamond: 1,
}

UNIQUE_ITEMS = {
    ItemType.GrandCharm: 1,
    ItemType.SmallCharm: 1,
    ItemType.Amulet: 1,
    ItemType.Ring: 1,
    ItemType.Jewel: 1,

    ItemType.DemonhideArmor: 0,
    ItemType.ChaosArmor: 0,
    ItemType.StuddedLeather: 0,
    ItemType.AncientArmor: 0,
    ItemType.GhostArmor: 0,
    ItemType.MagePlate: 0,
    ItemType.OrnatePlate: 0,
    ItemType.WireFleece: 0,
    ItemType.KrakenShell: 0,
    ItemType.BalrogSkin: 1,
    ItemType.SacredArmor: 1,
    ItemType.Cuirass: 0,
    ItemType.TemplarCoat: 1,
    ItemType.DuskShroud: 1,
    ItemType.MeshArmor: 0,
    ItemType.SerpentskinArmor: 1,
    ItemType.RussetArmor: 0,
    ItemType.EmbossedPlate: 0,
    ItemType.Sash: 0,
    ItemType.Belt: 0,
    ItemType.MeshBelt: 0,
    ItemType.VampirefangBelt: 0,
    ItemType.HeavyBelt: 0,
    ItemType.SharkskinBelt: 0,
    ItemType.BattleBelt: 0,
    ItemType.WarBelt: 1,
    ItemType.SpiderwebSash: 1,
    ItemType.MithrilCoil: 1,
    ItemType.DemonhideBoots: 0,
    ItemType.LightPlatedBoots: 0,
    ItemType.BoneweaveBoots: 1,
    ItemType.MeshBoots: 0,
    ItemType.SharkskinBoots: 0,
    ItemType.MyrmidonGreaves: 1,
    ItemType.WarBoots: 0,
    ItemType.BattleBoots: 1,
    ItemType.ScarabshellBoots: 1,
    ItemType.Boots: 0,
    ItemType.HeavyGloves: 0,
    ItemType.ChainGloves: 0,
    ItemType.VampireboneGloves: 1,
    ItemType.Gauntlets: 0,
    ItemType.LightGauntlets: 0,
    ItemType.OgreGauntlets: 1,
    ItemType.Vambraces: 0,
    ItemType.DemonhideGloves: 0,
    ItemType.HeavyBracers: 0,
    ItemType.SharkskinGloves: 0,
    ItemType.BattleGauntlets: 0,
    ItemType.WarGauntlets: 0,
    ItemType.SkullCap: 0,
    ItemType.WarHat: 0,
    ItemType.GrandCrown: 1,
    ItemType.BoneVisage: 1,
    ItemType.SpiredHelm: 1,
    ItemType.DemonHead: 1,
    ItemType.Corona: 2,
    ItemType.Diadem: 2,
    ItemType.Shako: 1,
    ItemType.Tiara: 1,
    ItemType.Casque: 0,
    ItemType.GrimHelm: 1,
    ItemType.WingedHelm: 0,
    ItemType.Basinet: 0,
    ItemType.Armet: 0,
    ItemType.DeathMask: 0,
    ItemType.Sallet: 0,
    ItemType.SlayerGuard: 1,
    ItemType.FuryVisor: 1,
    ItemType.BloodSpirit: 0,
    ItemType.TotemicMask: 0,
    ItemType.EarthSpirit: 1,
    ItemType.SkySpirit: 1,
    ItemType.SuccubusSkull: 1,
    ItemType.BloodlordSkull: 1,
    ItemType.HierophantTrophy: 1,
    ItemType.GrimWand: 0,
    ItemType.TombWand: 0,
    ItemType.BurntWand: 1,
    ItemType.LichWand: 0,
    ItemType.UnearthedWand: 1,
    ItemType.Buckler: 0,
    ItemType.Defender: 0,
    ItemType.RoundShield: 0,
    ItemType.GrimShield: 0,
    ItemType.TrollNest: 0,
    ItemType.Monarch: 1,
    ItemType.Luna: 0,
    ItemType.BarbedShield: 0,
    ItemType.BladeBarrier: 0,
    ItemType.Scutum: 0,
    ItemType.Aegis: 0,
    ItemType.TrollNest: 0,
    ItemType.DragonShield: 0,
    ItemType.Ward: 0,
    ItemType.ZakarumShield: 1,
    ItemType.SacredRondache: 0,
    ItemType.GildedShield: 1,
    ItemType.WingedAxe: 1,
    ItemType.WingedKnife: 1,
    ItemType.FlyingAxe: 0,
    ItemType.Scourge: 1,
    ItemType.BoneKnife: 0,
    ItemType.Dagger: 0,
    ItemType.ThunderMaul: 0,
    ItemType.LegendaryMallet: 1,
    ItemType.Tulwar: 0,
    ItemType.PhaseBlade: 0,
    ItemType.ElderStaff: 0,
    ItemType.ArchonStaff: 1,
    ItemType.QuarterStaff: 1,
    ItemType.DivineScepter: 0,
    ItemType.MightyScepter: 1,
    ItemType.EttinAxe: 1,
    ItemType.DimensionalShard: 1,
    ItemType.EldritchOrb: 1,
    ItemType.SwirlingCrystal: 0,
    ItemType.Thresher: 1,
    ItemType.CrypticAxe: 1,
    ItemType.OgreAxe: 0,
    ItemType.MatriarchalJavelin: 0,
    ItemType.CeremonialJavelin: 1,
    ItemType.HydraBow: 1,
    ItemType.CeremonialBow: 0,
    ItemType.MatriarchalBow: 0,
    ItemType.BattleCestus: 0,
    ItemType.GreaterTalons: 0,
    ItemType.WristSword: 0,
    ItemType.FeralClaws: 0,
}

SET_ITEMS = {
    ItemType.Amulet: 0,
    ItemType.Ring: 0,
    ItemType.BattleBoots: 0,
    ItemType.HuntersGuise: 0,
    ItemType.ShadowPlate: 0,
    ItemType.MythicalSword: 0,
    ItemType.OrnatePlate: 0,
    ItemType.Caduceus: 1,
    ItemType.VortexShield: 0,
    ItemType.OrnatePlate: 0,
    ItemType.WingedHelm: 0,
    ItemType.RoundShield: 0,
    ItemType.SacredArmor: 1,
    ItemType.AvengerGuard: 0,
    ItemType.WarGauntlets: 0,
    ItemType.WarBoots: 0,
    ItemType.OgreMaul: 0,
    ItemType.WarBelt: 0,
    ItemType.BrambleMitts: 0,
    ItemType.GrandMatronBow: 0,
    ItemType.Diadem: 0,
    ItemType.KrakenShell: 0,
    ItemType.BattleGauntlets: 0,
    ItemType.SharkskinBelt: 0,
    ItemType.MeshBoots: 0,
    ItemType.LoricatedMail: 0,
    ItemType.ScissorsSuwayyah: 0,
    ItemType.GrimHelm: 0,
    ItemType.SwirlingCrystal: 0,
    ItemType.MeshBelt: 0,
    ItemType.LacqueredPlate: 2,
    ItemType.DeathMask: 0,
    ItemType.HeavyBracers: 0,
    ItemType.TrollBelt: 1,
    ItemType.CantorTrophy: 0,
    ItemType.BoneVisage: 0,
    ItemType.ChaosArmor: 0,
    ItemType.ChainGloves: 0,
}

MAGIC_ITEMS = {
    ItemType.GrandCharm: 1,
    ItemType.LargeCharm: 0,
    ItemType.SmallCharm: 1,
    ItemType.Jewel: 0,

    ItemType.Monarch: 0,
}

RARE_ITEMS = {
    ItemType.Jewel: 0,
}

SUPERIOR_ITEMS = {
    (ItemType.MagePlate, 4): 1,
    (ItemType.MagePlate, 3): 1,
    (ItemType.MagePlate, 0): 1,
    (ItemType.ArchonPlate, 4): 1,
    (ItemType.ArchonPlate, 3): 1,
    (ItemType.ArchonPlate, 0): 1,
    (ItemType.DuskShroud, 4): 1,
    (ItemType.DuskShroud, 3): 1,
    (ItemType.DuskShroud, 0): 1,

    (ItemType.PhaseBlade, 6): 1,
    (ItemType.PhaseBlade, 5): 1,
    (ItemType.PhaseBlade, 0): 1,
    (ItemType.ColossusSword, 5): 1,
    (ItemType.ColossusSword, 0): 1,
}

NORMAL_ITEMS = {
    (ItemType.MagePlate, 3): 0,
    (ItemType.MagePlate, 0): 1,

    (ItemType.PhaseBlade, 6): 0,
    (ItemType.PhaseBlade, 5): 1,
    (ItemType.PhaseBlade, 0): 0,
    (ItemType.ColossusBlade, 6): 0,
    (ItemType.ColossusBlade, 5): 0,
    (ItemType.ColossusBlade, 0): 0,
    (ItemType.ColossusSword, 5): 1,
    (ItemType.ColossusSword, 0): 1,
}

SUPERIOR_ETH_ITEMS = {
    (ItemType.LacqueredPlate, 4): 1,
    (ItemType.LacqueredPlate, 3): 1,
    (ItemType.LacqueredPlate, 0): 1,
    (ItemType.SacredArmor, 4): 1,
    (ItemType.SacredArmor, 3): 1,
    (ItemType.SacredArmor, 0): 1,
    (ItemType.ArchonPlate, 4): 1,
    (ItemType.ArchonPlate, 3): 1,
    (ItemType.ArchonPlate, 0): 1,
    (ItemType.GreatHauberk, 4): 1,
    (ItemType.GreatHauberk, 3): 1,
    (ItemType.GreatHauberk, 0): 1,
    (ItemType.Wyrmhide, 4): 1,
    (ItemType.Wyrmhide, 3): 1,
    (ItemType.Wyrmhide, 0): 1,
    (ItemType.DuskShroud, 4): 1,
    (ItemType.DuskShroud, 3): 1,
    (ItemType.DuskShroud, 0): 1,

    (ItemType.Thresher, 4): 1,
    (ItemType.Thresher, 0): 0,
    (ItemType.GreatPoleaxe, 4): 1,
    (ItemType.GreatPoleaxe, 0): 0,
    (ItemType.GiantThresher, 4): 1,
    (ItemType.GiantThresher, 0): 0,
    (ItemType.CrypticAxe, 4): 1,
    (ItemType.CrypticAxe, 0): 0,
    (ItemType.ColossusVoulge, 4): 0,
    (ItemType.ColossusVoulge, 0): 0,

    (ItemType.ColossusBlade, 6): 1,
    (ItemType.ColossusBlade, 5): 0,
    (ItemType.ColossusBlade, 0): 1,
    (ItemType.ColossusSword, 5): 0,
    (ItemType.ColossusSword, 0): 0,
}

NORMAL_ETH_ITEMS = {
    (ItemType.LacqueredPlate, 4): 0,
    (ItemType.LacqueredPlate, 3): 0,
    (ItemType.LacqueredPlate, 0): 0,
    (ItemType.SacredArmor, 4): 0,
    (ItemType.SacredArmor, 3): 0,
    (ItemType.SacredArmor, 0): 0,
    (ItemType.ArchonPlate, 4): 0,
    (ItemType.ArchonPlate, 3): 0,
    (ItemType.ArchonPlate, 0): 0,
    (ItemType.GreatHauberk, 4): 0,
    (ItemType.GreatHauberk, 3): 0,
    (ItemType.GreatHauberk, 0): 0,
    (ItemType.Wyrmhide, 4): 0,
    (ItemType.Wyrmhide, 3): 0,
    (ItemType.Wyrmhide, 0): 0,
    (ItemType.DuskShroud, 4): 0,
    (ItemType.DuskShroud, 3): 0,
    (ItemType.DuskShroud, 0): 0,
    
    (ItemType.Thresher, 4): 1,
    (ItemType.Thresher, 0): 1,
    (ItemType.GreatPoleaxe, 4): 1,
    (ItemType.GreatPoleaxe, 0): 1,
    (ItemType.GiantThresher, 4): 1,
    (ItemType.GiantThresher, 0): 1,
    (ItemType.CrypticAxe, 4): 1,
    (ItemType.CrypticAxe, 0): 1,
    (ItemType.ColossusVoulge, 4): 0,
    (ItemType.ColossusVoulge, 0): 0,
    (ItemType.ColossusBlade, 6): 0,
    (ItemType.ColossusBlade, 5): 0,
    (ItemType.ColossusBlade, 0): 0,
    (ItemType.ColossusSword, 5): 0,
    (ItemType.ColossusSword, 0): 0,
}
