using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MapAssist.Types
{
    public enum Missile
    {
        Arrow = 0,
        Javelin = 1,
        Bighead1 = 2,
        Bighead2 = 3,
        Bighead3 = 4,
        Bighead4 = 5,
        Bighead5 = 6,
        Spike1 = 7,
        Spike2 = 8,
        Spike3 = 9,
        Spike4 = 10,
        Spike5 = 11,
        Firearrow = 12,
        Cr_Arrow1 = 13,
        Cr_Arrow2 = 14,
        Cr_Arrow3 = 15,
        Cr_Arrow4 = 16,
        Cr_Arrow5 = 17,
        Blood1 = 18,
        Blood2 = 19,
        Bigblood1 = 20,
        Bigblood2 = 21,
        Shafire1 = 22,
        Shafire2 = 23,
        Shafire3 = 24,
        Shafire4 = 25,
        Shafire5 = 26,
        Magicarrow = 27,
        Icearrow = 28,
        Fireexplode = 29,
        Iceexplode = 30,
        Bolt = 31,
        Andarielspray = 32,
        Bigheadexp = 33,
        Shamanexp = 34,
        Throwaxe = 35,
        Throwknife = 36,
        Glaive = 37,
        Poisonjav = 38,
        Poisonjavcloud = 39,
        Coldarrow = 40,
        Explodingarrow = 41,
        Explodingarrowexp = 42,
        Plaguejavelin = 43,
        Oilpotion = 44,
        Explosivepotion = 45,
        Fulminatingpotion = 46,
        Rancidgasepotion = 47,
        Chokinggaspoition = 48,
        Stranglinggaspotion = 49,
        Notused50 = 50,
        Explosivepotionexp = 51,
        Explosivepotiondebris1 = 52,
        Explosivepotiondebris2 = 53,
        Explosivepotiondebris3 = 54,
        Holybolt = 55,
        Chargedbolt = 56,
        Sanctuarybolt = 57,
        Firebolt = 58,
        Icebolt = 59,
        Infernoflame1 = 60,
        Infernoflame2 = 61,
        Fireball = 62,
        Mummy1 = 63,
        Mummy2 = 64,
        Mummy3 = 65,
        Mummy4 = 66,
        Blaze = 67,
        Firewallmaker = 68,
        Firewall = 69,
        Goospit1 = 70,
        Goospit2 = 71,
        Goospit3 = 72,
        Goospit4 = 73,
        Goospit5 = 74,
        Goosplat = 75,
        SandPile = 76,
        Unholybolt1 = 77,
        Unholybolt2 = 78,
        Unholybolt3 = 79,
        Unholybolt4 = 80,
        Sanctuarycenter = 81,
        Fireexplosion = 82,
        Stuckarrow = 83,
        Footprint = 84,
        Immolationarrow = 85,
        Guidedarrow = 86,
        Freezingarrow = 87,
        Freezingarrowexp1 = 88,
        Freezingarrowexp2 = 89,
        Nova = 90,
        Iceblast = 91,
        Blessedhammer = 92,
        Chainlightning = 93,
        Fistofares = 94,
        Chillblood = 95,
        Glacialspike = 96,
        Teleport = 97,
        Lightningbolt = 98,
        Lightninghit = 99,
        Meteor = 100,
        Meteorcenter = 101,
        Meteortail = 102,
        Meteorexplode = 103,
        Firesmall = 104,
        Firemedium = 105,
        Monblizcenter = 106,
        Monbliz1 = 107,
        Monbliz2 = 108,
        Monbliz3 = 109,
        Monbliz4 = 110,
        Monblizexplode1 = 111,
        Monblizexplode2 = 112,
        Monblizexplode3 = 113,
        Teeth = 114,
        Corpseexplosion = 115,
        Poisoncorpseexplosion = 116,
        Monstercorpseexplode = 117,
        Poisonnova = 118,
        Frostnova = 119,
        Rogue1 = 120,
        Rogue2 = 121,
        Rogue3 = 122,
        BatLightningBolt = 123,
        BatLightningTrail = 124,
        Skmage1 = 125,
        Skmage2 = 126,
        Skmage3 = 127,
        Skmage4 = 128,
        Vampirefireball = 129,
        Vampirefirewallmaker = 130,
        Vampirefirewall = 131,
        Vampiremeteor = 132,
        Vampiremeteorcenter = 133,
        Vampiremeteorexp = 134,
        Raven1 = 135,
        Raven2 = 136,
        Amphibiangoo1 = 137,
        Amphibiangoo2 = 138,
        Tentaclegoo = 139,
        Amphibianexplode = 140,
        Poisonpuff = 141,
        Curseeffectred = 142,
        Spidergoolay = 143,
        Fetishinferno1 = 144,
        Fetishinferno2 = 145,
        Spidergoo = 146,
        Cursecast = 147,
        Howl = 148,
        Shout = 149,
        Dust = 150,
        Redlightmissile = 151,
        Greenlightmissile = 152,
        Bluelightmissile = 153,
        Whitelightmissile = 154,
        Corpsepoisoncloud = 155,
        Chillbloodcloud = 156,
        Chillbloodpuff = 157,
        Blizzardcenter = 158,
        Blizzard1 = 159,
        Blizzard2 = 160,
        Blizzard3 = 161,
        Blizzard4 = 162,
        Blizzardexplode1 = 163,
        Blizzardexplode2 = 164,
        Blizzardexplode3 = 165,
        Thunderstorm1 = 166,
        Thunderstorm2 = 167,
        Thunderstorm3 = 168,
        Thunderstorm4 = 169,
        Monsterlight = 170,
        Poisonball = 171,
        Diablight = 172,
        Redemption = 173,
        Redemptionfail = 174,
        Handofgod = 175,
        Diabfire = 176,
        Fingermagespider = 177,
        ElectricThrowaxe = 178,
        Diabwallmaker = 179,
        Diabwall = 180,
        Curseamplifydamage = 181,
        Cursedimvision = 182,
        Curseweaken = 183,
        Curseironmaiden = 184,
        Curseterror = 185,
        Curseattract = 186,
        Cursereversevampire = 187,
        Curseconfuse = 188,
        Cursedecrepify = 189,
        Curselowerresist = 190,
        Cursecenter = 191,
        Bonespear = 192,
        Bonespirit = 193,
        Coldunique = 194,
        Lightunique = 195,
        Skbowarrow1 = 196,
        Skbowarrow2 = 197,
        Skbowarrow3 = 198,
        Skbowarrow4 = 199,
        Skbowarrow5 = 200,
        Nova1 = 201,
        Nova2 = 202,
        Andypoisonbolt = 203,
        Teethexplode = 204,
        Lightningjavelin = 205,
        Lightningfury = 206,
        Bonewallmaker = 207,
        Necromage1 = 208,
        Necromage2 = 209,
        Necromage3 = 210,
        Necromage4 = 211,
        Sparkle = 212,
        Multipleshotarrow = 213,
        Multipleshotbolt = 214,
        Chargedstrikebolt = 215,
        Bonespearexplode = 216,
        Poisonexplosioncloud = 217,
        Bonecast = 218,
        Battlecry = 219,
        Primepoisoncloud = 220,
        Plaguejavcloud = 221,
        Rancidgascloud = 222,
        Chokinggascloud = 223,
        Stranglinggascloud = 224,
        Buglightning = 225,
        Pantherjav1 = 226,
        Pantherjav2 = 227,
        Pantherjav3 = 228,
        Pantherjav4 = 229,
        Immolationfire = 230,
        Furylightning = 231,
        Lightningstrike = 232,
        Fistoftheheavensdelay = 233,
        Fistoftheheavensbolt = 234,
        Warcry = 235,
        Battlecommand = 236,
        Battleorders = 237,
        Pantherpotorange = 238,
        Pantherpotgreen = 239,
        Meteorfire = 240,
        TrapSpikeRight = 241,
        TrapSpikeLeft = 242,
        TrapCursedSkullRight = 243,
        TrapCursedSkullLeft = 244,
        TrapPoisonBallRight = 245,
        TrapPoisonBallLeft = 246,
        Hydra = 247,
        Bonespeartrail = 248,
        Grimwardsmallstart = 249,
        Grimwardsmall = 250,
        Grimwardsmallstop = 251,
        Grimwardmediumstart = 252,
        Grimwardmedium = 253,
        Grimwardmediumstop = 254,
        Grimwardlargestart = 255,
        Grimwardlarge = 256,
        Grimwardlargestop = 257,
        Zakarumlight = 258,
        Grimwardscare = 259,
        Frozenorb = 260,
        Frozenorbbolt = 261,
        Frozenorbnova = 262,
        Frozenorbexplode = 263,
        Chillingarmorbolt = 264,
        Fireexplosion2 = 265,
        Blowgun = 266,
        Chainlightning2 = 267,
        Revivesmall = 268,
        Revivemedium = 269,
        Revivelarge = 270,
        Monglacialspike = 271,
        Icebreaksmall = 272,
        Icebreakmedium = 273,
        Icebreaklarge = 274,
        Icebreaksmoke = 275,
        Mephisto = 276,
        Firehead = 277,
        Whilrwind = 278,
        Arcanelightningbolt = 279,
        Frogfire = 280,
        Frogcold = 281,
        Frogpois = 282,
        Desertfireball = 283,
        Brdeathcontrol = 284,
        Brdeathlightningbolt = 285,
        Brdeathlightninghit = 286,
        Denofevillight = 287,
        Cairnstones = 288,
        Cairnstonessky = 289,
        Cairnstonesground = 290,
        Towermist = 291,
        Towermisttrail = 292,
        Brdeathsmokes1 = 293,
        Brdeathsmokenu = 294,
        Brdeathsmokedt = 295,
        Brdeathspirits1 = 296,
        Brdeathspiritnu = 297,
        Brdeathspiritdt = 298,
        Mephistodeathcontrol = 299,
        Mephistofirewallmaker = 300,
        Mephistofirewall = 301,
        Mephistoflyingrocksbig = 302,
        Mephistoexplosionbig = 303,
        Mephistoflyingrockssmall = 304,
        Mephistoexplosionsmall = 305,
        Mephistodonotdraw = 306,
        Andycontrol0 = 307,
        Andyfirewallmaker = 308,
        Andyfirewall = 309,
        Andycolumnfirebase = 310,
        Andycolumnfire = 311,
        Andyfallingdebris1 = 312,
        Andyfallingdebris2 = 313,
        Andyfallingdebris3 = 314,
        Andydebrisexplosion1 = 315,
        Andydebrisexplosion2 = 316,
        Andydebrisexplosion3 = 317,
        Andydebrisexplosion4 = 318,
        Andydebrisexplosion5 = 319,
        Willowisplightningbolt = 320,
        Queenpoisoncloud = 321,
        DirtPile = 322,
        Undeadmissile1 = 323,
        Undeadmissile2 = 324,
        Undeadmissile3 = 325,
        Undeadmissile4 = 326,
        Bonespiritexplode = 327,
        Dopplezonexplode = 328,
        Monbonespirit = 329,
        Towermistfade = 330,
        Countessfirewall = 331,
        Towerchestspawner = 332,
        Hellmeteorlaunch1 = 333,
        Hellmeteorlaunch2 = 334,
        Hellmeteorup = 335,
        Hellmeteordown = 336,
        Hellmeteorball = 337,
        Horadricstaff = 338,
        Horadriclightning = 339,
        Horadriclight = 340,
        Regurgitatorcorpse = 341,
        Regurgitatorcorpseexpl = 342,
        Highpriestlightning = 343,
        Icebreaksmallmelt = 344,
        Icebreaklargemelt = 345,
        Leapknockback = 346,
        Radamentdeath = 347,
        Radamenthandofgod = 348,
        Radamentholybolt = 349,
        Taintedsuncontrol = 350,
        Taintedsunflash = 351,
        Taintedsunball = 352,
        Queendeathcenter = 353,
        Queendeathglob = 354,
        Queendeathsplat1 = 355,
        Queendeathsplat2 = 356,
        Healingbolt = 357,
        Mephistoholedelay = 358,
        Mephistoholebirth = 359,
        Mephistoholeneutral = 360,
        Mephistoholedeath = 361,
        Mephistoholedead = 362,
        Durieldeathcontrol = 363,
        Durieldeathrock = 364,
        Durieldeathdebris = 365,
        Durieldeathsmoke = 366,
        Mephistoexplosion = 367,
        Orbmist = 368,
        Orbmisttrail = 369,
        Orbmistfade = 370,
        Pilum = 371,
        DiabloAppears = 372,
        Hfcontrol = 373,
        Hffragment1 = 374,
        Hffragment2 = 375,
        Hffragment3 = 376,
        Hfspirit1 = 377,
        Hfreserved3 = 378,
        IzualControl = 379,
        IzualMistLoop = 380,
        IzualMistFade = 381,
        IzualLightning = 382,
        IzualLightningTrail = 383,
        CairnStonesBolt = 384,
        BombInAir = 385,
        BombOnGround = 386,
        BombExplosion = 387,
        ShockFieldInAir = 388,
        ShockFieldOnGround = 389,
        Throwingstar = 390,
        Acidspray = 391,
        BladeCreeper = 392,
        Distraction = 393,
        DistractionFog = 394,
        DistractionPuff = 395,
        DistractionStart = 396,
        DistractionEnd = 397,
        Impinfernoflame1 = 398,
        Impinfernoflame2 = 399,
        Baallightningbolt = 400,
        Baallightningtrail = 401,
        Baallightningbolt2 = 402,
        Baallightningtrail2 = 403,
        Impfireball = 404,
        Impfireballexplode = 405,
        CatapultchargedballOn = 406,
        Catapultchargedball = 407,
        Catapultchargedballbolt = 408,
        ImpSpawnMonsters = 409,
        CatapultSpikeBallOn = 410,
        CatapultSpikeBall = 411,
        CatapultSpikeInAir = 412,
        CatapultSpikeOnGround = 413,
        CatapultSpikeExplosion = 414,
        CatapultColdBallOn = 415,
        CatapultColdBall = 416,
        CatapultColdExplosion = 417,
        CatapultPlagueBallOn = 418,
        CatapultPlagueBall = 419,
        CatapultPlagueCloud = 420,
        CatapultMeteorBallOn = 421,
        CatapultMeteorBall = 422,
        CatapultMeteorFire = 423,
        TowerDeath = 424,
        HealingVortex = 425,
        Suicidecorpseexplode = 426,
        Suicidefireexplode = 427,
        Suicideiceexplode = 428,
        Explodingjavalin = 429,
        Explodingjavalinexp = 430,
        Lightingtrailingjavalin = 431,
        Lightjavalintrail = 432,
        Lightjavalinexplosion = 433,
        Icejavalin = 434,
        Icejavalinexplode = 435,
        Plaguejavelin2 = 436,
        Plaguejavlinexplode = 437,
        Advlighttrailingjav = 438,
        Advlighttrailingjav2 = 439,
        Advlightjavexplode = 440,
        Sucfireball = 441,
        Sucfireballexplode = 442,
        Sucfireballtrail = 443,
        Sucshockfieldmissile = 444,
        Sucshockfieldmissileexp = 445,
        Sucshockfield = 446,
        Hellfiremissile = 447,
        Hellfireexa = 448,
        Hellfireexb = 449,
        ImpChargedBolt = 450,
        ImpTeleport = 451,
        Moltenboulder = 452,
        Moltenboulderemerge = 453,
        Moltenboulderexplode = 454,
        Moltenboulderfirepath = 455,
        MoltenboulderFlyingrocks = 456,
        Firestorm = 457,
        Firestormmaker = 458,
        Arcticblast1 = 459,
        Arcticblast2 = 460,
        ErruptionCenter = 461,
        ErruptionCrack1 = 462,
        ErruptionCrack2 = 463,
        ErruptionSmoke1 = 464,
        ErruptionSmoke2 = 465,
        VineBeastWalk1 = 466,
        VineBeastWalk2 = 467,
        VineBeastNeutral = 468,
        VineBeastAttack = 469,
        VineBeastDeath = 470,
        Vines = 471,
        VinesTrail = 472,
        VinesWither = 473,
        PlagueVines = 474,
        PlagueVinesTrail = 475,
        PlagueVinesWither = 476,
        Twister = 477,
        Tornado = 478,
        Volcano = 479,
        VolcanoOverlayFire = 480,
        VolcanoDebris2 = 481,
        VolcanoExplosion = 482,
        VolcanoSmallFire = 483,
        DragonbreathMissile = 484,
        Lureprojectile = 485,
        Lurecenter = 486,
        Lurecloud = 487,
        Impmiss1 = 488,
        Impmiss2 = 489,
        Impmiss3 = 490,
        Impmiss4 = 491,
        Impmiss5 = 492,
        FrozenhorrorArcticblast1 = 493,
        FrozenhorrorArcticblast2 = 494,
        Sentrychargedbolt = 495,
        Sentryspikeinair = 496,
        Sentryspikeonground = 497,
        RecyclerDelay = 498,
        RecyclerVine = 499,
        RecyclerFade = 500,
        RecyclerExplosion = 501,
        DeathMauler = 502,
        DeathMaulerTrail = 503,
        DeathMaulerTrailFade = 504,
        Bladefury1 = 505,
        Bladefragment1 = 506,
        Bladefury2 = 507,
        Bladefragment2 = 508,
        Bladefury3 = 509,
        Bladefragment3 = 510,
        Shockwave = 511,
        Lightningtalons = 512,
        Lightningtalonstrail = 513,
        Phoenixtrail = 514,
        Rabiesplague = 515,
        Rabiescontagion = 516,
        WakeOfDestructionMaker = 517,
        WakeOfDestruction = 518,
        Deathsentryexplode = 519,
        Tigerfury = 520,
        Tigerfurytrail = 521,
        Tigerfurytrail2 = 522,
        InfernoSentry1 = 523,
        InfernoSentry2 = 524,
        AncientThrowingAxe = 525,
        Sentrylightningbolt = 526,
        Sentrylightninghit = 527,
        AnyaCenter = 528,
        AnyaIcicle = 529,
        AnyaIceimpact = 530,
        AnyaIcesteam = 531,
        AnyaIcemagic = 532,
        DragontailMissile = 533,
        Dragonflight = 534,
        Dragonflightmaker = 535,
        ProgressiveRadiusDamage = 536,
        VineBeastWalk1Fade = 537,
        VineBeastWalk2Fade = 538,
        VineBeastNeutralFade = 539,
        VineRecyclerDelay = 540,
        AncientDeathCenter = 541,
        AncientDeathCloud = 542,
        LightningChargeUpNova = 543,
        ChainlightningchargeUp = 544,
        PainWormAppear = 545,
        BaalTauntControl = 546,
        BaalTauntLightning = 547,
        BaalTauntLightningTrail = 548,
        BaalTauntPoison = 549,
        BaalSpawnMonsters = 550,
        MindblastHit = 551,
        BladeShieldMissile = 552,
        BladeShieldAttachment = 553,
        BaalInferno = 554,
        BaalNova = 555,
        Fistsoffireexplode = 556,
        Fistsoffirefirewall = 557,
        Clawsofthunderbolt = 558,
        Clawsofthundernova = 559,
        Bladesoficeexplode = 560,
        Bladesoficecubes = 561,
        Bladesoficecubesmelt = 562,
        Royalstrikemeteor = 563,
        Royalstrikemeteorcenter = 564,
        Royalstrikemeteortail = 565,
        Royalstrikemeteorexplode = 566,
        Royalstrikemeteorfire = 567,
        Royalstrikechainlightning = 568,
        Royalstrikechaosice = 569,
        WorldStoneChip1 = 570,
        WorldStoneChip2 = 571,
        WorldStoneChip3 = 572,
        WorldStoneChip4 = 573,
        Highpriestlightning2 = 574,
        Infernoflame3 = 575,
        MindblastCenter = 576,
        Armageddoncontrol = 577,
        Armageddonrock = 578,
        Armageddontail = 579,
        Armageddonexplosion = 580,
        Hurricaneswoosh = 581,
        Hurricanecart = 582,
        Hurricanerock = 583,
        Hurricanesack = 584,
        Hurricanetree = 585,
        Hurricanevase = 586,
        Baalcorpseexplodedelay = 587,
        Baalcorpseexplodeexpl = 588,
        BaalColdMaker = 589,
        BaalColdTrail = 590,
        BaalSpawnMonstersExp = 591,
        Impmiss21 = 592,
        Impmiss22 = 593,
        Impmiss23 = 594,
        Impmiss24 = 595,
        Impmiss25 = 596,
        Anyasteam1 = 597,
        Anyasteam2 = 598,
        Ancientsguide = 599,
        Ancientsmarker = 600,
        Ancientscontrol = 601,
        Overseercontrol = 602,
        Nihlithak1 = 603,
        Nihlithak2 = 604,
        Nihlithak3 = 605,
        Nihlathakcontrol = 606,
        Nihlathakswoosh = 607,
        Nihlathakdebris1 = 608,
        Nihlathakdebris2 = 609,
        Nihlathakdebris3 = 610,
        Nihlathakdebris4 = 611,
        Nihlathakglow = 612,
        Baalteleport = 613,
        Baalclonedeath = 614,
        Anyasteamvent = 615,
        Anyasteam = 616,
        Nihlathakhole = 617,
        Nihlathakholelight = 618,
        Volcanofiretrail = 619,
        Nihlathakglow2 = 620,
        Nihlathakbonechips = 621,
        Baalcorpseexplodefade = 622,
        Armageddonfire = 623,
        Icesparkle = 624,
        BaalfxControl = 625,
        BaalfxSpirit1 = 626,
        BaalfxSpirit2 = 627,
        BaalfxSpirit3 = 628,
        BaalfxSpirit4 = 629,
        BaalfxSpirit5 = 630,
        BaalfxBaalHeadAppear = 631,
        BaalfxBaalHead1 = 632,
        BaalfxBaalHead2 = 633,
        BaalfxBaalHead3 = 634,
        BaalfxTyrealDebris1 = 635,
        BaalfxTyrealDebris2 = 636,
        BaalfxTyrealDebris3 = 637,
        BaalfxTyrealDebrisBreak = 638,
        WorldstoneShake = 639,
        Blessedhammerex = 640,
        Sentrylightningbolt2 = 641,
        Sentrylightninghit2 = 642,
        Lightningtowernova = 643,
        Skbowarrow6 = 644,
        Skbowarrow7 = 645,
        Skbowarrow8 = 646,
        Bighead6 = 647,
        Viper_Poisjav = 648,
        Viper_Poisjavcloud = 649,
        Viper_Fire = 650,
        Viper_Firecloud = 651,
        Viper_Bonespear = 652,
        Countessfirewallmaker = 653,
        BaalTauntLightningControl = 654,
        BaalTauntPoisonControl = 655,
        Explodingarrowexp2 = 656,
        Freezingarrowexp3 = 657,
        Pantherjav5 = 658,
        Spike6 = 659,
        Cr_Arrow6 = 660,
        Skmagepois = 661,
        Skmagecold = 662,
        Skmagefire = 663,
        Skmageltng = 664,
        Succubusmiss = 665,
        Willowisplightningbolt2 = 666,
        Mummyex = 667,
        Goospitex = 668,
        Impmissex = 669,
        Diablogeddoncontrol = 670,
        Diablogeddonrock = 671,
        Diablogeddontail = 672,
        Diablogeddonexplosion = 673,
        Diablogeddonfire = 674,
        Megademoninferno = 675,
        Trapfirebolt = 676,
        Trappoisonjavcloud = 677,
        Trapnova = 678,
        Mephfrostnova = 679,
        Mephlight = 680,
        Vampiremeteorfire = 681,
        Strafearrow = 682,
        Strafebolt = 683,
        Recklessattacksmissile = 684
    }

    public static class MissileTypes
    {
        public static readonly Dictionary<uint, MissileType> _MissileTypes = new Dictionary<uint, MissileType>()
        {
            { 0, MissileType.PhysicalLarge },
            { 31, MissileType.PhysicalLarge },
            { 115, MissileType.PhysicalLarge },
            { 135, MissileType.PhysicalLarge },
            { 136, MissileType.PhysicalLarge },
            { 426, MissileType.PhysicalLarge },
            { 525, MissileType.PhysicalLarge },
            { 2, MissileType.PhysicalSmall },
            { 3, MissileType.PhysicalSmall },
            { 4, MissileType.PhysicalSmall },
            { 5, MissileType.PhysicalSmall },
            { 6, MissileType.PhysicalSmall },
            { 7, MissileType.PhysicalSmall },
            { 8, MissileType.PhysicalSmall },
            { 9, MissileType.PhysicalSmall },
            { 10, MissileType.PhysicalSmall },
            { 11, MissileType.PhysicalSmall },
            { 35, MissileType.PhysicalSmall },
            { 36, MissileType.PhysicalSmall },
            { 37, MissileType.PhysicalSmall },
            { 120, MissileType.PhysicalSmall },
            { 121, MissileType.PhysicalSmall },
            { 122, MissileType.PhysicalSmall },
            { 213, MissileType.PhysicalSmall },
            { 214, MissileType.PhysicalSmall },
            { 241, MissileType.PhysicalSmall },
            { 242, MissileType.PhysicalSmall },
            { 243, MissileType.PhysicalSmall },
            { 244, MissileType.PhysicalSmall },
            { 266, MissileType.PhysicalSmall },
            { 410, MissileType.PhysicalSmall },
            { 411, MissileType.PhysicalSmall },
            { 412, MissileType.PhysicalSmall },
            { 413, MissileType.PhysicalSmall },
            { 414, MissileType.PhysicalSmall },
            { 502, MissileType.PhysicalSmall },
            { 503, MissileType.PhysicalSmall },
            { 504, MissileType.PhysicalSmall },
            { 22, MissileType.FireLarge },
            { 23, MissileType.FireLarge },
            { 24, MissileType.FireLarge },
            { 25, MissileType.FireLarge },
            { 26, MissileType.FireLarge },
            { 29, MissileType.FireLarge },
            { 60, MissileType.FireLarge },
            { 61, MissileType.FireLarge },
            { 62, MissileType.FireLarge },
            { 68, MissileType.FireLarge },
            { 69, MissileType.FireLarge },
            { 82, MissileType.FireLarge },
            { 100, MissileType.FireLarge },
            { 101, MissileType.FireLarge },
            { 103, MissileType.FireLarge },
            { 129, MissileType.FireLarge },
            { 130, MissileType.FireLarge },
            { 131, MissileType.FireLarge },
            { 132, MissileType.FireLarge },
            { 133, MissileType.FireLarge },
            { 134, MissileType.FireLarge },
            { 265, MissileType.FireLarge },
            { 247, MissileType.FireLarge },
            { 404, MissileType.FireLarge },
            { 405, MissileType.FireLarge },
            { 554, MissileType.FireLarge },
            { 12, MissileType.FireSmall },
            { 41, MissileType.FireSmall },
            { 42, MissileType.FireSmall },
            { 51, MissileType.FireSmall },
            { 52, MissileType.FireSmall },
            { 53, MissileType.FireSmall },
            { 54, MissileType.FireSmall },
            { 58, MissileType.FireSmall },
            { 67, MissileType.FireSmall },
            { 85, MissileType.FireSmall },
            { 102, MissileType.FireSmall },
            { 104, MissileType.FireSmall },
            { 105, MissileType.FireSmall },
            { 127, MissileType.FireSmall },
            { 144, MissileType.FireSmall },
            { 145, MissileType.FireSmall },
            { 172, MissileType.FireSmall },
            { 176, MissileType.FireSmall },
            { 179, MissileType.FireSmall },
            { 180, MissileType.FireSmall },
            { 230, MissileType.FireSmall },
            { 240, MissileType.FireSmall },
            { 277, MissileType.FireSmall },
            { 280, MissileType.FireSmall },
            { 283, MissileType.FireSmall },
            { 324, MissileType.FireSmall },
            { 300, MissileType.FireSmall },
            { 301, MissileType.FireSmall },
            { 398, MissileType.FireSmall },
            { 399, MissileType.FireSmall },
            { 427, MissileType.FireSmall },
            { 441, MissileType.FireSmall },
            { 442, MissileType.FireSmall },
            { 443, MissileType.FireSmall },
            { 447, MissileType.FireSmall },
            { 448, MissileType.FireSmall },
            { 449, MissileType.FireSmall },
            { 452, MissileType.FireSmall },
            { 453, MissileType.FireSmall },
            { 454, MissileType.FireSmall },
            { 455, MissileType.FireSmall },
            { 456, MissileType.FireSmall },
            { 457, MissileType.FireSmall },
            { 458, MissileType.FireSmall },
            { 480, MissileType.FireSmall },
            { 483, MissileType.FireSmall },
            { 556, MissileType.FireSmall },
            { 557, MissileType.FireSmall },
            { 563, MissileType.FireSmall },
            { 564, MissileType.FireSmall },
            { 565, MissileType.FireSmall },
            { 566, MissileType.FireSmall },
            { 567, MissileType.FireSmall },
            { 592, MissileType.FireSmall },
            { 619, MissileType.FireSmall },
            { 623, MissileType.FireSmall },
            { 650, MissileType.FireSmall },
            { 651, MissileType.FireSmall },
            { 653, MissileType.FireSmall },
            { 663, MissileType.FireSmall },
            { 674, MissileType.FireSmall },
            { 676, MissileType.FireSmall },
            { 681, MissileType.FireSmall },
            { 87, MissileType.IceLarge },
            { 88, MissileType.IceLarge },
            { 89, MissileType.IceLarge },
            { 91, MissileType.IceLarge },
            { 96, MissileType.IceLarge },
            { 106, MissileType.IceLarge },
            { 119, MissileType.IceLarge },
            { 158, MissileType.IceLarge },
            { 260, MissileType.IceLarge },
            { 262, MissileType.IceLarge },
            { 263, MissileType.IceLarge },
            { 271, MissileType.IceLarge },
            { 679, MissileType.IceLarge },
            { 28, MissileType.IceSmall },
            { 40, MissileType.IceSmall },
            { 59, MissileType.IceSmall },
            { 107, MissileType.IceSmall },
            { 108, MissileType.IceSmall },
            { 109, MissileType.IceSmall },
            { 110, MissileType.IceSmall },
            { 111, MissileType.IceSmall },
            { 112, MissileType.IceSmall },
            { 113, MissileType.IceSmall },
            { 126, MissileType.IceSmall },
            { 156, MissileType.IceSmall },
            { 157, MissileType.IceSmall },
            { 159, MissileType.IceSmall },
            { 160, MissileType.IceSmall },
            { 161, MissileType.IceSmall },
            { 162, MissileType.IceSmall },
            { 163, MissileType.IceSmall },
            { 164, MissileType.IceSmall },
            { 165, MissileType.IceSmall },
            { 194, MissileType.IceSmall },
            { 212, MissileType.IceSmall },
            { 261, MissileType.IceSmall },
            { 264, MissileType.IceSmall },
            { 281, MissileType.IceSmall },
            { 415, MissileType.IceSmall },
            { 416, MissileType.IceSmall },
            { 417, MissileType.IceSmall },
            { 493, MissileType.IceSmall },
            { 494, MissileType.IceSmall },
            { 662, MissileType.IceSmall },
            { 93, MissileType.LightLarge },
            { 98, MissileType.LightLarge },
            { 97, MissileType.LightLarge },
            { 99, MissileType.LightLarge },
            { 166, MissileType.LightLarge },
            { 167, MissileType.LightLarge },
            { 168, MissileType.LightLarge },
            { 169, MissileType.LightLarge },
            { 215, MissileType.LightLarge },
            { 225, MissileType.LightLarge },
            { 267, MissileType.LightLarge },
            { 276, MissileType.LightLarge },
            { 279, MissileType.LightLarge },
            { 558, MissileType.LightLarge },
            { 559, MissileType.LightLarge },
            { 568, MissileType.LightLarge },
            { 574, MissileType.LightLarge },
            { 55, MissileType.LightSmall },
            { 56, MissileType.LightSmall },
            { 57, MissileType.LightSmall },
            { 77, MissileType.LightSmall },
            { 78, MissileType.LightSmall },
            { 79, MissileType.LightSmall },
            { 80, MissileType.LightSmall },
            { 90, MissileType.LightSmall },
            { 123, MissileType.LightSmall },
            { 124, MissileType.LightSmall },
            { 128, MissileType.LightSmall },
            { 170, MissileType.LightSmall },
            { 195, MissileType.LightSmall },
            { 201, MissileType.LightSmall },
            { 202, MissileType.LightSmall },
            { 205, MissileType.LightSmall },
            { 206, MissileType.LightSmall },
            { 231, MissileType.LightSmall },
            { 232, MissileType.LightSmall },
            { 233, MissileType.LightSmall },
            { 234, MissileType.LightSmall },
            { 320, MissileType.LightSmall },
            { 326, MissileType.LightSmall },
            { 339, MissileType.LightSmall },
            { 340, MissileType.LightSmall },
            { 343, MissileType.LightSmall },
            { 382, MissileType.LightSmall },
            { 383, MissileType.LightSmall },
            { 384, MissileType.LightSmall },
            { 400, MissileType.LightSmall },
            { 401, MissileType.LightSmall },
            { 402, MissileType.LightSmall },
            { 403, MissileType.LightSmall },
            { 406, MissileType.LightSmall },
            { 407, MissileType.LightSmall },
            { 408, MissileType.LightSmall },
            { 431, MissileType.LightSmall },
            { 432, MissileType.LightSmall },
            { 433, MissileType.LightSmall },
            { 438, MissileType.LightSmall },
            { 439, MissileType.LightSmall },
            { 440, MissileType.LightSmall },
            { 512, MissileType.LightSmall },
            { 513, MissileType.LightSmall },
            { 526, MissileType.LightSmall },
            { 527, MissileType.LightSmall },
            { 534, MissileType.LightSmall },
            { 535, MissileType.LightSmall },
            { 543, MissileType.LightSmall },
            { 544, MissileType.LightSmall },
            { 547, MissileType.LightSmall },
            { 548, MissileType.LightSmall },
            { 641, MissileType.LightSmall },
            { 642, MissileType.LightSmall },
            { 643, MissileType.LightSmall },
            { 654, MissileType.LightSmall },
            { 666, MissileType.LightSmall },
            { 678, MissileType.LightSmall },
            { 680, MissileType.LightSmall },
            { 664, MissileType.LightSmall },
            { 32, MissileType.PoisonLarge },
            { 116, MissileType.PoisonLarge },
            { 118, MissileType.PoisonLarge },
            { 549, MissileType.PoisonLarge },
            { 38, MissileType.PoisonSmall },
            { 39, MissileType.PoisonSmall },
            { 43, MissileType.PoisonSmall },
            { 45, MissileType.PoisonSmall },
            { 46, MissileType.PoisonSmall },
            { 47, MissileType.PoisonSmall },
            { 48, MissileType.PoisonSmall },
            { 49, MissileType.PoisonSmall },
            { 63, MissileType.PoisonSmall },
            { 64, MissileType.PoisonSmall },
            { 65, MissileType.PoisonSmall },
            { 66, MissileType.PoisonSmall },
            { 70, MissileType.PoisonSmall },
            { 71, MissileType.PoisonSmall },
            { 72, MissileType.PoisonSmall },
            { 73, MissileType.PoisonSmall },
            { 74, MissileType.PoisonSmall },
            { 75, MissileType.PoisonSmall },
            { 125, MissileType.PoisonSmall },
            { 137, MissileType.PoisonSmall },
            { 138, MissileType.PoisonSmall },
            { 139, MissileType.PoisonSmall },
            { 140, MissileType.PoisonSmall },
            { 141, MissileType.PoisonSmall },
            { 143, MissileType.PoisonSmall },
            { 146, MissileType.PoisonSmall },
            { 155, MissileType.PoisonSmall },
            { 171, MissileType.PoisonSmall },
            { 203, MissileType.PoisonSmall },
            { 217, MissileType.PoisonSmall },
            { 220, MissileType.PoisonSmall },
            { 221, MissileType.PoisonSmall },
            { 222, MissileType.PoisonSmall },
            { 223, MissileType.PoisonSmall },
            { 224, MissileType.PoisonSmall },
            { 245, MissileType.PoisonSmall },
            { 246, MissileType.PoisonSmall },
            { 282, MissileType.PoisonSmall },
            { 323, MissileType.PoisonSmall },
            { 418, MissileType.PoisonSmall },
            { 419, MissileType.PoisonSmall },
            { 420, MissileType.PoisonSmall },
            { 648, MissileType.PoisonSmall },
            { 649, MissileType.PoisonSmall },
            { 661, MissileType.PoisonSmall },
            { 148, MissileType.MagicLarge },
            { 149, MissileType.MagicLarge },
            { 92, MissileType.MagicLarge },
            { 142, MissileType.MagicLarge },
            { 192, MissileType.MagicLarge },
            { 193, MissileType.MagicLarge },
            { 204, MissileType.MagicLarge },
            { 235, MissileType.MagicLarge },
            { 236, MissileType.MagicLarge },
            { 237, MissileType.MagicLarge },
            { 287, MissileType.MagicLarge },
            { 555, MissileType.MagicLarge },
            { 546, MissileType.MagicLarge },
            { 550, MissileType.MagicLarge },
            { 587, MissileType.MagicLarge },
            { 588, MissileType.MagicLarge },
            { 589, MissileType.MagicLarge },
            { 590, MissileType.MagicLarge },
            { 591, MissileType.MagicLarge },
            { 665, MissileType.MagicLarge },
            { 27, MissileType.MagicSmall },
            { 83, MissileType.MagicSmall },
            { 84, MissileType.MagicSmall },
            { 81, MissileType.MagicSmall },
            { 86, MissileType.MagicSmall },
            { 114, MissileType.MagicSmall },
            { 147, MissileType.MagicSmall },
            { 173, MissileType.MagicSmall },
            { 174, MissileType.MagicSmall },
            { 177, MissileType.MagicSmall },
            { 181, MissileType.MagicSmall },
            { 182, MissileType.MagicSmall },
            { 183, MissileType.MagicSmall },
            { 184, MissileType.MagicSmall },
            { 185, MissileType.MagicSmall },
            { 186, MissileType.MagicSmall },
            { 187, MissileType.MagicSmall },
            { 188, MissileType.MagicSmall },
            { 189, MissileType.MagicSmall },
            { 190, MissileType.MagicSmall },
            { 191, MissileType.MagicSmall },
            { 216, MissileType.MagicSmall },
            { 218, MissileType.MagicSmall },
            { 219, MissileType.MagicSmall },
            { 248, MissileType.MagicSmall },
            { 268, MissileType.MagicSmall },
            { 269, MissileType.MagicSmall },
            { 270, MissileType.MagicSmall },
            { 278, MissileType.MagicSmall },
            { 325, MissileType.MagicSmall },
            { 327, MissileType.MagicSmall },
            { 328, MissileType.MagicSmall },
            { 329, MissileType.MagicSmall },
            { 451, MissileType.MagicSmall },
            { 425, MissileType.MagicSmall },
            { 541, MissileType.MagicSmall },
            { 542, MissileType.MagicSmall },
            { 640, MissileType.MagicSmall },
            { 652, MissileType.MagicSmall }
        };
    }

    public enum MissileType
    {
        PhysicalLarge,
        PhysicalSmall,
        FireLarge,
        FireSmall,
        IceLarge,
        IceSmall,
        LightLarge,
        LightSmall,
        PoisonLarge,
        PoisonSmall,
        MagicLarge,
        MagicSmall
    }
}
